window_size: 5
train_start_date: 2018-10-20 13:30:00
train_end_date: 2021-11-10 9:30:00
valid_start_date: 2021-11-10 10:30:00
valid_end_date: 2024-01-6 10:30:00
features: Date, open, High, Low, close, volume #make sure to have Date High Low
indicators_names: rsi macd